### PR TITLE
Add wrap file for libspng-0.4.2

### PR DESCRIPTION
**Pull request by randy408**

### CODE REVIEW

**Comment by sarum9in** [comment]
Unfortunately this will not build as your archive contains nested libspng-0.4.2 directory:
```shell
$ unzip -t libspng-0.4.2.zip
... skipped
    testing: libspng-0.4.2/libspng-0.4.2/meson.build   OK
... skipped
```

This is not a regular setup for the source code archive you might want to fix that. Alternatively you might want to try specifying `directory = libspng-0.4.2/libspng-0.4.2`, not sure if it will work but we can try.

**Comment by randy408** [comment]
For this release the .zip had the wrong directory structure, I repackaged it.

**Comment by sarum9in** [comment]
Now the hash doesn't match.

```
 expected: 096e956b311972026d6d263ea16d8e44c2116d1c174d8e69acb90a5ac2ee2bc2
      got: 7786a5d5b35bc871527c866c9a07f54d475261b32e876c7d264805a9e768c1fe
```

**Comment by randy408** [comment]
The hash now matches https://libspng.org/libspng-0.4.2.zip.sha256sum.

**Pull request merged**
